"""empty message

Revision ID: 37de532cb008
Revises: 3196cf694e52
Create Date: 2024-04-16 16:59:41.100243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37de532cb008'
down_revision = '3196cf694e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
