"""empty message

Revision ID: 467d62967653
Revises: d0e63fb1742a
Create Date: 2024-04-12 23:35:37.144718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467d62967653'
down_revision = 'd0e63fb1742a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('work_orders_license_plate_key', type_='unique')
        batch_op.drop_constraint('work_orders_vin_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('work_orders_vin_key', ['vin'])
        batch_op.create_unique_constraint('work_orders_license_plate_key', ['license_plate'])

    # ### end Alembic commands ###
