"""empty message

Revision ID: 814d0fd168ae
Revises: d26e9e4c0645
Create Date: 2024-04-16 16:27:55.610530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814d0fd168ae'
down_revision = 'd26e9e4c0645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name='images_work_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey'),
    sa.UniqueConstraint('public_id', name='images_public_id_key')
    )
    # ### end Alembic commands ###
