"""empty message

Revision ID: ecb836be343e
Revises: 6ef70e925632
Create Date: 2024-04-02 15:58:36.119941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb836be343e'
down_revision = '6ef70e925632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('work_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('work_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
